import orchestrator from "tests/orchestrator.js";
import { version as uuidVersion } from "uuid";
import user from "models/user.js";
import password from "models/password.js";

const baseUrl = process.env.TEST_BASE_URL || "http://localhost:3000";

beforeAll(async () => {
  await orchestrator.waitForAllServices();
  await orchestrator.clearDatabase();
  await orchestrator.runPendingMigrations();
});

describe("PATCH /api/v1/users/[username]", () => {
  describe("Anonymous user", () => {
    test("with non existent `username`", async () => {
      const response = await fetch(`${baseUrl}/api/v1/users/InexistentUser`, {
        method: "PATCH",
      });
      expect(response.status).toBe(404);

      const responseBody = await response.json();

      expect(responseBody).toEqual({
        name: "NotFoundError",
        message: "Usuário não encontrado no sistema.",
        action: "Verifique o nome do usuario e tente novamente.",
        statusCode: 404,
      });
    });

    test("with duplicated `username`", async () => {
      const user1response = await fetch(`${baseUrl}/api/v1/users`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          username: "user1",
          email: "user1@example.com",
          password: "password123",
        }),
      });
      expect(user1response.status).toBe(201);

      const user2response = await fetch(`${baseUrl}/api/v1/users`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          username: "user2",
          email: "user2@example.com",
          password: "password123",
        }),
      });
      expect(user2response.status).toBe(201);

      const response = await fetch(`${baseUrl}/api/v1/users/user2`, {
        method: "PATCH",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          username: "user1",
        }),
      });
      expect(response.status).toBe(400);

      const responseBody = await response.json();

      expect(responseBody).toEqual({
        name: "ValidationError",
        message: "Username já esta sendo utilizado.",
        action: "Por favor, utilize outro username.",
        statusCode: 400,
      });
    });

    test("with duplicated `email`", async () => {
      const user1response = await fetch(`${baseUrl}/api/v1/users`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          username: "email1",
          email: "email1@example.com",
          password: "password123",
        }),
      });
      expect(user1response.status).toBe(201);

      const user2response = await fetch(`${baseUrl}/api/v1/users`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          username: "email2",
          email: "email2@example.com",
          password: "password123",
        }),
      });
      expect(user2response.status).toBe(201);

      const response = await fetch(`${baseUrl}/api/v1/users/email2`, {
        method: "PATCH",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          email: "email1@example.com",
        }),
      });
      expect(response.status).toBe(400);

      const responseBody = await response.json();

      expect(responseBody).toEqual({
        name: "ValidationError",
        message: "Email já esta sendo utilizado.",
        action: "Por favor, utilize outro email.",
        statusCode: 400,
      });
    });

    test("with unique `username`", async () => {
      const user1response = await fetch(`${baseUrl}/api/v1/users`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          username: "uniqueusername1",
          email: "uniqueuser1@example.com",
          password: "password123",
        }),
      });
      expect(user1response.status).toBe(201);

      const response = await fetch(`${baseUrl}/api/v1/users/uniqueusername1`, {
        method: "PATCH",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          username: "uniqueusername2",
        }),
      });
      expect(response.status).toBe(200);

      const responseBody = await response.json();

      expect(responseBody).toEqual({
        id: responseBody.id, // The ID will be generated by the database, so we can't assert its exact value
        username: "uniqueusername2",
        email: "uniqueuser1@example.com",
        password: responseBody.password,
        created_at: responseBody.created_at, // The created_at timestamp will be generated by the database, so we can't assert its exact value
        updated_at: responseBody.updated_at, // The updated_at timestamp will be generated by the database, so we can't assert its exact value
      });

      expect(uuidVersion(responseBody.id)).toBe(4);
      expect(Date.parse(responseBody.created_at)).not.toBeNaN();
      expect(Date.parse(responseBody.updated_at)).not.toBeNaN();

      expect(responseBody.updated_at > responseBody.created_at).toBe(true);
    });

    test("with unique `email`", async () => {
      const user1response = await fetch(`${baseUrl}/api/v1/users`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          username: "uniqueemail1",
          email: "uniqueemail1@example.com",
          password: "password123",
        }),
      });
      expect(user1response.status).toBe(201);

      const response = await fetch(`${baseUrl}/api/v1/users/uniqueemail1`, {
        method: "PATCH",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          email: "uniqueemail2@example.com",
        }),
      });
      expect(response.status).toBe(200);

      const responseBody = await response.json();

      expect(responseBody).toEqual({
        id: responseBody.id, // The ID will be generated by the database, so we can't assert its exact value
        username: "uniqueemail1",
        email: "uniqueemail2@example.com",
        password: responseBody.password,
        created_at: responseBody.created_at, // The created_at timestamp will be generated by the database, so we can't assert its exact value
        updated_at: responseBody.updated_at, // The updated_at timestamp will be generated by the database, so we can't assert its exact value
      });

      expect(uuidVersion(responseBody.id)).toBe(4);
      expect(Date.parse(responseBody.created_at)).not.toBeNaN();
      expect(Date.parse(responseBody.updated_at)).not.toBeNaN();

      expect(responseBody.updated_at > responseBody.created_at).toBe(true);
    });

    test("with new `password`", async () => {
      const user1response = await fetch(`${baseUrl}/api/v1/users`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          username: "newPassword1",
          email: "newPassword1@example.com",
          password: "newPassord1",
        }),
      });
      expect(user1response.status).toBe(201);

      const response = await fetch(`${baseUrl}/api/v1/users/newPassword1`, {
        method: "PATCH",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          password: "newPassword2",
        }),
      });
      expect(response.status).toBe(200);

      const responseBody = await response.json();

      expect(responseBody).toEqual({
        id: responseBody.id, // The ID will be generated by the database, so we can't assert its exact value
        username: "newPassword1",
        email: "newPassword1@example.com",
        password: responseBody.password,
        created_at: responseBody.created_at, // The created_at timestamp will be generated by the database, so we can't assert its exact value
        updated_at: responseBody.updated_at, // The updated_at timestamp will be generated by the database, so we can't assert its exact value
      });

      expect(uuidVersion(responseBody.id)).toBe(4);
      expect(Date.parse(responseBody.created_at)).not.toBeNaN();
      expect(Date.parse(responseBody.updated_at)).not.toBeNaN();

      expect(responseBody.updated_at > responseBody.created_at).toBe(true);

      const userInDatabase = await user.findOneByUsername("newPassword1");
      const correctPasswordMatch = await password.compare(
        "newPassword2",
        userInDatabase.password,
      );
      const incorrectPasswordMatch = await password.compare(
        "newPassword1",
        userInDatabase.password,
      );

      expect(correctPasswordMatch).toBe(true);
      expect(incorrectPasswordMatch).toBe(false);
    });
  });
});
